version: "3"
services:
  app:
    image: tid-app-dev
    build:
      context: ../app
      dockerfile: Dockerfile.development
    container_name: tid-app-dev-c
    volumes:
      - ../app:/app
      - node_modules:/client/node_modules/
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
volumes:
  node_modules:
