version: "3"
services:
  app:
    image: tid-app-prod
    build:
      context: ../app
      dockerfile: Dockerfile.production
    container_name: tid-app-prod-c
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
